# Generated by Django 5.2.6 on 2025-10-07 09:40

from django.db import migrations

scenarios = [
    {
        "id": 1,
        "title": "Going to the Barbershop",
        "slug": "barbershop",
        "description": "Practice a dialogue between a customer and a barber.",
    },
    {
        "id": 2,
        "title": "At the Restaurant",
        "slug": "restaurant",
        "description": "Practice ordering food and interacting with restaurant staff.",
    },
    {
        "id": 3,
        "title": "Booking a Hotel Room",
        "slug": "hotel",
        "description": "Practice checking in and making requests at a hotel.",
    },
    {
        "id": 4,
        "title": "Asking for Directions",
        "slug": "directions",
        "description": "Practice asking for and giving directions in a new city.",
    },
    {
        "id": 5,
        "title": "Shopping for Clothes",
        "slug": "shopping",
        "description": "Practice interacting with sales staff while shopping for clothes.",
    },
    {
        "id": 6,
        "title": "Visiting the Doctor",
        "slug": "doctor",
        "description": "Practice describing symptoms and understanding medical advice.",
    },
    {
        "id": 7,
        "title": "At the Airport",
        "slug": "airport",
        "description": "Practice checking in, going through security, and boarding a flight.",
    },
    {
        "id": 8,
        "title": "Making Small Talk",
        "slug": "small-talk",
        "description": "Practice casual conversations on various topics.",
    },
]

def populate_scenarios(apps, schema_editor):
    Scenario = apps.get_model('core', 'Scenario')
    for scenario in scenarios:
        Scenario.objects.update_or_create(
            id=scenario["id"],
            defaults={
                "title": scenario["title"],
                "slug": scenario["slug"],
                "description": scenario["description"],
            }
        )
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_scenarios),
    ]
